env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  no-console:
    - error
    - allow:
      - warn
      - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
